######
# This file includes the code to output a private confidence interval, using private mean 
# and variance estimators generated by Algorithm 7 Symmetric quantiles and simulation
# as introduced in Algorithm 3. 
######

#install.packages("rmutil")
#install.packages("here")
library(rmutil)
library(here)
source(here("algorithms/alg5_EXPQ.R"))


############
# The function priv_exp_ci() takes up to 6 parameters and returns a differentially private
# confidence interval: 
#   db:     Normally distributed sample data as a vector of numbers. 
#   a:      Significance level (set a = 0.05, the function outputs 95% confidence interval).
#   e:      Privacy parameter epsilon.
#   xmin:   Given lower bound of the data range.
#   xmax:   Given upper bound of the data range.
#   b:      Choice of the lower quantile. The upper quantile will be indicated by 1-b. 
#           (e.g. If want to use the first and third quartiles, do b = 0.25). Set in default
#           to the optimized value. 
############
priv_double_ci <- function(db, a, e, xmin, xmax, b = .35) {
  n <- length(db)
  db <- sort(db)
  bottom <- priv_median_c(db, b, e/2, xmin, xmax, TRUE)
  top <- priv_median_c(db, 1 - b,  e/2, xmin, xmax, TRUE)
  m <- (bottom + top)/2
  std <- max(0, (top - m)/qnorm(1 - b))
  
  sims <- 1:1000
  for(i in 1:1000) {
    sim_db <- sort(rnorm(n, m, std))
    sim_bottom <- priv_median_c(sim_db, b, e/2, xmin, xmax, TRUE)
    sim_top <- priv_median_c(sim_db, 1 - b,  e/2, xmin, xmax, TRUE)
    sims[i] <- (sim_bottom + sim_top)/2
  }
  moe <- diff(as.double(quantile(sims, c(a/2, 1 - a/2))))/2
  return(c(m - moe, m + moe))
}