######
# This file includes the code to output a private confidence interval, using private mean 
# and variance estimators generated by Algorithm 8 Median of Deviations and simulation
# as introduced in Algorithm 3. 
######

#install.packages("rmutil")
#install.packages("here")
library(rmutil)
library(here)
source(here("algorithms/alg5_EXPQ.R"))

############
# The function priv_exp_ci_abs() takes up to 6 parameters and returns a differentially private
# confidence interval: 
#   db:     Normally distributed sample data as a vector of numbers. 
#   a:      Significance level (set a = 0.05, the function outputs 95% confidence interval).
#   e:      Privacy parameter epsilon.
#   xmin:   Given lower bound of the data range.
#   xmax:   Given upper bound of the data range.
#   p:      Allocation of the privacy parameter epsilon. 100p% of the privacy budget is consumed
#             by generating the private mean; the rest is consumed by generating the private
#             variance. Set in default to the optimized value. 
############
priv_exp_ci_abs <- function(db, a, e, xmin, xmax, p = .5) {
  n <- length(db)
  db <- sort(db)
  m <- priv_median_c(db, .5, p*e, xmin, xmax, TRUE)
  std <- priv_median_c(abs(db-m), .5, (1-p) * e, 0, (xmax - xmin)) * (1/qnorm(.75))
  
  sims <- 1:1000
  for(i in 1:1000) {
    sim_db <- rnorm(n, m, std)
    sims[i] <- priv_median_c(sim_db, .5, p*e, xmin, xmax)
  }
  
  moe <- diff(as.double(quantile(sims, c(a/2, 1 - a/2))))/2
  return(c(m - moe, m + moe))
}
