### This file includes source code to produce the parameter allocation Optimation plot 
### as shown in Figure 12 in Appendix.
library(tidyverse)

## The dataset is generated by running simulation on NOISYVAR with privacy parameter
## allocation varied. 
data <- read_csv("data/lap_params.csv")

facet_names <- c("100" = "n = 100", 
                 "500" = "n = 500", 
                 "1000" = "n = 1000", 
                 "5000" = "n = 5000")
facet_names <- as_labeller(facet_names)

lap_params <- data %>% 
  ggplot(aes(y = moe, x = p, col = as.factor(e))) + 
  facet_wrap(~n, labeller = facet_names) + 
  geom_line() +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x), 
                labels = trans_format("log10", math_format(10^.x))) + 
  labs(x = "\u03C1", 
       y = "Margin of Error", 
       col = "\u03B5")+
  theme(legend.position = "bottom") +
  theme(panel.background = element_rect(fill = "white", colour = "grey70"), 
        panel.grid.major = element_line(colour = "grey90"), 
        panel.grid.minor = element_line(colour = "grey90"), 
        strip.background = element_rect(colour = "grey70", fill = "grey90"), 
        legend.key = element_rect(colour = "white", fill = "white"), 
        legend.box.background = element_rect(colour = "grey80"), 
        legend.box.margin = margin(6, 6, 6, 6))

ggsave("lap_params.png", path = "paper/plots", lap_params, device = "png")
