### This file includes source code to produce the parameter allocation Optimation plot 
### as shown in Figure 14 in Appendix.
library(tidyverse)

## The dataset is generated by running simulation on CENQ with b, the percentile used for
## generating private measure of spread, varied. 
data <- read_csv("data/median_params.csv")

facet_names <- c("100" = "n = 100",
                 "500" = "n = 500", 
                 "1000" = "n = 1000", 
                 "5000" = "n = 5000")
facet_names <- as_labeller(facet_names)

median_params <- data %>% ggplot(aes(y = moe, x = b, col = as.factor(e))) +
  facet_wrap(~n, labeller = facet_names) +
  geom_line() +
  labs(y = "Margin of Error",
       col = "\u03B5")+
  theme(legend.position = "bottom") +
  theme(panel.background = element_rect(fill = "white", colour = "grey70"), 
        panel.grid.major = element_line(colour = "grey90"), 
        panel.grid.minor = element_line(colour = "grey90"), 
        strip.background = element_rect(colour = "grey70", fill = "grey90"), 
        legend.key = element_rect(colour = "white", fill = "white"), 
        legend.box.background = element_rect(colour = "grey80"), 
        legend.box.margin = margin(6, 6, 6, 6))

ggsave("median_params.png", path = "paper/plots", median_params, device = "png")
